server:
  port: 9001
gateway:
  routes:
    - id: service-sample
      uri: http://127.0.0.1:9000
      predicates:
        - Path=/api/sample/**,/api/service-sample/**
      filters:
        - StripPrefix=2
