server:
  port: 9001
gateway:
  routes:
    - id: service-sample
      uri: http://127.0.0.1:9000
      predicates:
        - Path=/abc/**,/def/**
        - Path=/api/service-sample/**,/sample/**
      filters:
        - StripPrefix=2
