gateway:
  routes:
    - id: service1-sample
#      uri: http://127.0.0.1:9000
      uri: lb://panda-service-sample
      order: 1
      predicates:
#        - Path=/api/service-sample/**,=/api/sample/**
#        - Cookie=Name,\d+
#        - Header=X-B3-TraceId,\d+
#        - Method=POST,GET
#        - Query=name,Lewis
#        - ClientIp=127.0.0.1,192.168.200.111
#        - Between=2019-04-29T00:00:00+08:00[Asia/Shanghai], 2030-05-01T00:00:00+08:00[Asia/Shanghai]
#        - Before=2030-05-01T00:00:00+08:00[Asia/Shanghai]
#        - After=2019-04-29T00:00:00+08:00[Asia/Shanghai]
        - Weight=service-sample,1
      filters:
        - StripPrefix=2
    - id: service2-sample
      uri: lb://panda-service-sample
      order: 2
      predicates:
        - Weight=service-sample,8
      filters:
        - StripPrefix=2
